@echo off
echo Iniciando techstore-eureka (8761)...
start cmd /k "cd techstore-eureka && mvnw spring-boot:run"
timeout /t 15

echo Iniciando ms_usuario (8081)...
start cmd /k "cd ms_usuario && mvnw spring-boot:run"
echo Iniciando ms_producto (8082)...
start cmd /k "cd ms_producto && mvnw spring-boot:run"
echo Iniciando ms_orden (8083)...
start cmd /k "cd ms_orden && mvnw spring-boot:run"
echo Iniciando ms_pago (8084)...
start cmd /k "cd ms_pago && mvnw spring-boot:run"
timeout /t 20

echo Iniciando techstore-gateway (8090)...
start cmd /k "cd techstore-gateway && mvnw spring-boot:run"
