CREATE DATABASE IF NOT EXISTS ms_usuario_db;
CREATE DATABASE IF NOT EXISTS ms_producto_db;
CREATE DATABASE IF NOT EXISTS ms_orden_db;
CREATE DATABASE IF NOT EXISTS ms_pago_db;
CREATE DATABASE IF NOT EXISTS ms_despacho_db;
CREATE DATABASE IF NOT EXISTS ms_notificacion_db;
CREATE DATABASE IF NOT EXISTS ms_resena_db;
CREATE DATABASE IF NOT EXISTS ms_soporte_db;