server:
  port: 8090

spring:
  application:
    name: techstore-gateway

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

      routes:
        - id: usuarios_route
          uri: lb://ms-usuario
          predicates:
            - Path=/api/v1/usuarios/**, /ms-usuario/api-docs/**

        - id: productos_route
          uri: lb://ms-producto
          predicates:
            - Path=/api/v1/productos/**, /api/v1/categorias/**, /api/v1/marcas/**, /api/v1/inventarios/**, /ms-producto/api-docs/**

        - id: ordenes_route
          uri: lb://ms-orden
          predicates:
            - Path=/api/v1/ordenes/**, /api/v1/carrito-detalle/**, /api/v1/detalle-orden/**, /ms-orden/api-docs/**

        - id: pagos_route
          uri: lb://ms-pago
          predicates:
            - Path=/api/v1/pagos/**, /api/v1/envios/**, /ms-pago/api-docs/**

        - id: resenas_route
          uri: lb://ms-resena
          predicates:
            - Path=/api/v1/resenas/**, /ms-resena/api-docs/**

        - id: soporte_route
          uri: lb://ms-soporte
          predicates:
            - Path=/api/v1/tickets/**, /ms-soporte/api-docs/**

        - id: despacho_route
          uri: lb://ms-despacho
          predicates:
            - Path=/api/v1/despachos/**, /ms-despacho/api-docs/**

        - id: notificacion_route
          uri: lb://ms-notificacion
          predicates:
            - Path=/api/v1/notificaciones/**, /ms-notificacion/api-docs/**

        - id: swagger_ui_route
          uri: lb://ms-usuario
          predicates:
            - Path=/swagger-ui/**, /v3/api-docs/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true