server:
  port: 8082

spring:
  application:
    name: ms-producto
  profiles:
    active: dev

springdoc:
  api-docs:
    path: /ms-producto/api-docs
  swagger-ui:
    path: /swagger-ui/index.html

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

---
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:mysql://localhost:3306/ms_producto_db?createDatabaseIfNotExist=true
    username: root
    password: ''
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

---
spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: jdbc:mysql://localhost:3306/ms_producto_db_prod?createDatabaseIfNotExist=true
    username: root
    password: ''
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
