server:
  port: 8081

spring:
  application:
    name: ms-usuario
  
  datasource:
    url: jdbc:mysql://localhost:3306/ms_usuario_db
    username: root
    password: ''
    driver-class-name: com.mysql.cj.jdbc.Driver
  
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

springdoc:
  api-docs:
    path: /ms-usuario/api-docs
  swagger-ui:
    path: /swagger-ui/index.html

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true



